### ISSUE TITLE
UX/UI Ref

### ISSUE THREAD

**Issue by emmanuel1will** [eccentricality/hollywoodHackers#3]
Break up prototype into div/class tags

**Comment by eulagee** [comment]
Breaking down project to container, header, body, nav, aside, paragraph, figure and footer.

**Comment by emmanuel1will** [comment]
![hhgroup-mock-001](https://user-images.githubusercontent.com/17571044/119738855-f9a10680-be46-11eb-8b42-3f8320957f2b.png)
