### ISSUE TITLE
OMDB API

### ISSUE THREAD

**Issue by eccentricality** [eccentricality/hollywoodHackers#6]

**Comment by eccentricality** [comment]
created functions to extract actor names into an array and dynamically create line items with each actor to be appended or internally utilized to link to individual actor pages.
![originalApi](https://user-images.githubusercontent.com/34589452/119742459-d7fb4b80-be55-11eb-9829-19c85fe4fd42.png)
![apiActorsParsed](https://user-images.githubusercontent.com/34589452/119742462-d9c50f00-be55-11eb-9546-d997f11290c7.png)
![actorsDynamicallyListed](https://user-images.githubusercontent.com/34589452/119742466-dc276900-be55-11eb-895a-197f3628f1ba.png)

**Comment by emmanuel1will** [comment]
We had to pivot our second api and are currently looking at the option of either a movie trailer api or popular movie quotes api
